### ISSUE TITLE
真心求问

### ISSUE THREAD

**Issue by abacteria** [LYL232/JAAPSS#1]
您好，您的代码写的很好，我想用他来做个前后端项目，想问下您知道怎么集成到springboot上吗，期待您的回复，谢谢🙏

**Comment by LYL232** [comment]
不好意思，不常上github，现在才看到。其实我的JAVA水平也不好，springboot没怎么用过，没有实际做过什么JAVA项目，就只能做做实验的水平，没啥经验，所以当初写的时候没有留接口，写成了命令行的形式，现在我也没太钻研JAVA，没多少时间，你可以看看src/pers/lyl232/jaapss/program/Command.java这个文件下的StartCommand类，这是执行求解程序的类，一般来说改改输入输出就可以用了吧。。。

**Comment by abacteria** [comment]
哈哈没事，你的代码写的很好，我学到很多，谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LYL232/JAAPSS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月11日(星期天) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LYL232/JAAPSS] 真心求问 (Issue #1)





 
不好意思，不常上github，现在才看到。其实我的JAVA水平也不好，springboot没怎么用过，没有实际做过什么JAVA项目，就只能做做实验的水平，没啥经验，所以当初写的时候没有留接口，写成了命令行的形式，现在我也没太钻研JAVA，没多少时间，你可以看看src/pers/lyl232/jaapss/program/Command.java这个文件下的StartCommand类，这是执行求解程序的类，一般来说改改输入输出就可以用了吧。。。
